using BUTR.CrashReport.Interfaces;
using BUTR.CrashReport.Models;

using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace Bannerlord.ButterLib.CrashReportWindow.Utils;

internal class StacktraceFilter : IStacktraceFilter
{
    private readonly MethodInfo? _bewFinalizer;
    public StacktraceFilter(MethodInfo? bewFinalizer)
    {
        _bewFinalizer = bewFinalizer;
    }

    public IEnumerable<StacktraceEntry> Filter(ICollection<StacktraceEntry> stacktraceEntries)
    {
        if (stacktraceEntries.Count == 1 && stacktraceEntries.First().ModuleInfo?.Id == "Bannerlord.Harmony")
            yield break;

        foreach (var stacktraceEntry in stacktraceEntries)
        {
            if (stacktraceEntry.ModuleInfo?.Id == "Bannerlord.ButterLib")
            {
                if (stacktraceEntry.Method == _bewFinalizer)
                {
                    continue;
                }
            }
            if (stacktraceEntry.ModuleInfo?.Id is "BetterExceptionWindow")
            {
                if (stacktraceEntry.Method is { Name: "Finalizer", DeclaringType: { Namespace: "AutoGeneratedExceptionFilter" } })
                {
                    continue;
                }
            }

            if (stacktraceEntry.ModuleInfo?.Id == "Bannerlord.MBOptionScreen")
            {
                if (stacktraceEntry.Method.Name == "ExecuteCommandPatch")
                {
                    continue;
                }
            }

            yield return stacktraceEntry;
        }
    }
}