using Bannerlord.ButterLib.ExceptionHandler;

namespace Bannerlord.ButterLib.Helpers
{
    internal static class CrashReportFilter
    {
        public static bool Filter(StacktraceEntry stacktraceEntry)
        {
            if (stacktraceEntry.ModuleInfo?.Id == "Bannerlord.ButterLib")
            {
                if (stacktraceEntry.Method == BEWPatch.FinalizerMethod)
                {
                    return false;
                }
            }
            if (stacktraceEntry.ModuleInfo?.Id is "BetterExceptionWindow")
            {
                if (stacktraceEntry.Method is { Name: "Finalizer", DeclaringType: { Namespace: "AutoGeneratedExceptionFilter" } })
                {
                    return false;
                }
            }

            if (stacktraceEntry.ModuleInfo?.Id == "Bannerlord.MBOptionScreen")
            {
                if (stacktraceEntry.Method.Name == "ExecuteCommandPatch")
                {
                    return false;
                }
            }

            return true;
        }
    }
}