name: DocFX

on:
  push:
    branches:
      #- master
      # documentation will cover the dev branch for now
      - dev
    paths:
      - '.github/workflows/docfx.yml'
      - 'src/Bannerlord.ButterLib/**.cs'
      - 'docs/**'
      - 'README.md'

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  docfx:
    name: DocFX documentation
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Download docfx
      uses: i3h/download-release-asset@v1
      with:
        owner: dotnet
        repo: docfx
        tag: latest
        file: docfx.zip

    - name: Extract docfx
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: docfx.zip
        pathTarget: docfx

    - name: Generating Newtonsoft.Json xref maps
      run: >-
        dotnet run -p build/SandcastleXrefGenerator -- `
            Newtonsoft.Json 11.0.2 netstandard2.0 `
            https://www.newtonsoft.com/json/help/html/ `
            $PWD/docs/xrefs/Newtonsoft.Json-xrefmap.yml
      shell: pwsh

    - name: Copy root README
      run: Copy-Item "README.md" -Destination "docs/index.md"
      shell: pwsh

    - name: Build Solution
      run: dotnet build src/Bannerlord.ButterLib/Bannerlord.ButterLib.csproj
      env:
        DOCFX: true
      shell: pwsh

    - name: Build DocFx.Plugin.LastModified
      run: dotnet build build/DocFx.Plugin.LastModified/DocFx.Plugin.LastModified --configuration Release --output docs/_template/last-modified/plugins
      shell: pwsh

    - name: DocFX metadata
      run: docfx/docfx.exe metadata docs/docfx.json
      env:
        DOCFX: true
      shell: pwsh

    - name: DocFX build
      run: docfx/docfx.exe build docs/docfx.json;
      shell: pwsh

    - name: Deploy DocFX
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/_site
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
